keyboard_vendor=0b05
keyboard_product=1b2c
keyboard_bt_mac=

display_top=2880x1800@120.000
display_bottom=2880x1800@120.000
display_scale=1.75
display_y_offset=1030

brightness_main=/sys/class/backlight/intel_backlight/brightness
brightness_bottom=/sys/class/backlight/card1-eDP-2-backlight/brightness

battery_limit=80
battery_path=/sys/class/power_supply/BAT0/charge_control_end_threshold

auto_display=1
auto_bluetooth=1
auto_brightness=1