Section "InputClass"
    Identifier "ELAN9008 touchscreen"
    MatchProduct "ELAN9008:00 04F3:425B"
    Driver "libinput"
    Option "MapToOutput" "eDP-1"
EndSection

Section "InputClass"
    Identifier "ELAN9009 touchscreen"
    MatchProduct "ELAN9009:00 04F3:425A"
    Driver "libinput"
    Option "MapToOutput" "eDP-2"
EndSection
