#!/bin/bash
# ============================================================================
# Zenbook Duo Linux - Persistent Configuration Manager
# Saves and restores all calibration parameters across reboots
# ============================================================================

CONFIG_DIR="/etc/zenbook-duo"
CONFIG_FILE="$CONFIG_DIR/zenbook-duo.conf"

echo "=============================================="
echo "  Zenbook Duo - Persistent Configuration"
echo "=============================================="
echo ""

# --- Create config directory if it doesn't exist ---
mkdir -p "$CONFIG_DIR"

# --- Save current configuration ---
save_config() {
    echo "Saving configuration..."
    
    # Get current display mode
    DISPLAY_MODE=$(duo status 2>/dev/null || echo "both")
    
    # Get current thermal profile
    THERMAL_PROFILE=$(cat /sys/devices/platform/asus-nb-wmi/platform-profile/platform-profile-0/profile 2>/dev/null || echo "balanced")
    
    # Get current keyboard backlight level
    KB_LEVEL=$(cat /tmp/zenbook-kb-backlight.state 2>/dev/null || echo "2")
    
    # Get current battery limit
    BATTERY_LIMIT=$(cat /sys/class/power_supply/BAT0/charge_control_end_threshold 2>/dev/null || echo "80")
    
    # Write config file
    cat > "$CONFIG_FILE" << EOF
# Zenbook Duo Configuration
# Generated by zenbook-config on $(date)

# Display
display_mode=$DISPLAY_MODE

# Thermal
thermal_profile=$THERMAL_PROFILE

# Keyboard backlight
keyboard_level=$KB_LEVEL

# Battery
battery_limit=$BATTERY_LIMIT

# Audio
audio_profile=zenbookduo

# WiFi
wifi_power_save=0
wifi_bt_coex=1
EOF
    
    echo "Configuration saved to $CONFIG_FILE"
}

# --- Restore configuration ---
restore_config() {
    echo "Restoring configuration..."
    
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "No configuration file found. Using defaults."
        return
    fi
    
    # Source the config file
    source "$CONFIG_FILE"
    
    # Restore display mode
    if [ -n "$display_mode" ]; then
        echo "Restoring display mode: $display_mode"
        duo "$display_mode" 2>/dev/null
    fi
    
    # Restore thermal profile
    if [ -n "$thermal_profile" ]; then
        echo "Restoring thermal profile: $thermal_profile"
        echo "$thermal_profile" | sudo tee /sys/devices/platform/asus-nb-wmi/platform-profile/platform-profile-0/profile >/dev/null 2>&1
    fi
    
    # Restore keyboard backlight
    if [ -n "$keyboard_level" ]; then
        echo "Restoring keyboard backlight: $keyboard_level"
        sudo -n python3 /usr/local/bin/bk.py "$keyboard_level" 2>/dev/null
        echo "$keyboard_level" > /tmp/zenbook-kb-backlight.state
    fi
    
    # Restore battery limit
    if [ -n "$battery_limit" ]; then
        echo "Restoring battery limit: $battery_limit%"
        echo "$battery_limit" | sudo tee /sys/class/power_supply/BAT0/charge_control_end_threshold >/dev/null 2>&1
    fi
    
    echo "Configuration restored."
}

# --- Show current configuration ---
show_config() {
    echo "Current Configuration:"
    echo ""
    
    if [ -f "$CONFIG_FILE" ]; then
        cat "$CONFIG_FILE" | grep -v "^#" | grep -v "^$"
    else
        echo "No configuration file found."
    fi
}

# --- Main ---
case "${1:-save}" in
    save)
        save_config
        ;;
    restore)
        restore_config
        ;;
    show)
        show_config
        ;;
    *)
        echo "Usage: $0 {save|restore|show}"
        echo ""
        echo "  save    - Save current settings to config file"
        echo "  restore - Restore settings from config file"
        echo "  show    - Show current configuration"
        ;;
esac
